version: "3.7"
services:
    # image project
    quizeiro:
        build: 
            args: 
                user: quizeiro
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on: 
            - redis
            - queue
        networks: 
            - quizeiro
    
    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - 80:80
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - quizeiro

    # db mysql
    mysql:
        image: mysql:8.1.0
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes: 
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports: 
            - 3306:3306
        networks: 
            - quizeiro

    # queue
    queue:
        build: 
            args: 
                user: quizeiro
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        command: "php laravel/artisan queue:work"
        volumes: 
            - ./:/var/www
        depends_on: 
            - redis
        networks: 
            - quizeiro

    # redis
    redis:
        image: redis:latest
        networks: 
            - quizeiro

networks: 
    quizeiro:
        driver: bridge